//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace userprofile.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ADMINISTRATION
    {
        public bool refsCanViewOthers { get; set; }
        public bool refsCanSeeOtherGames { get; set; }
        public int durationOfAlgorithm { get; set; }
        public Nullable<System.DateTime> algorithmStartDate { get; set; }
        public Nullable<System.DateTime> algorithmEndDate { get; set; }
        public bool algorithmAll { get; set; }
    }
}
