//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace userprofile.Models
{
    using System;
    using System.Collections.Generic;
    using System.Runtime.Serialization;

    public partial class AspNetUser : ISerializable
    {
        public AspNetUser()
        {
            this.APIKEYs = new HashSet<APIKEY>();
            this.AspNetUserClaims = new HashSet<AspNetUserClaim>();
            this.AspNetUserLogins = new HashSet<AspNetUserLogin>();
            this.Events = new HashSet<Event>();
            this.INFRACTIONS = new HashSet<INFRACTION>();
            this.PLAYERs = new HashSet<PLAYER>();
            this.REFEREEs = new HashSet<REFEREE>();
            this.TEAMs = new HashSet<TEAM>();
            this.TOURNAMENTs = new HashSet<TOURNAMENT>();
            this.AspNetRoles = new HashSet<AspNetRole>();
            this.TOURNAMENTs1 = new HashSet<TOURNAMENT>();
        }
    
        public string Id { get; set; }
        public Nullable<int> ffaNum { get; set; }
        public string UserName { get; set; }
        public string PasswordHash { get; set; }
        public string SecurityStamp { get; set; }
        public string firstName { get; set; }
        public string lastName { get; set; }
        public Nullable<int> phoneNum { get; set; }
        public string email { get; set; }
        public string photoDir { get; set; }
        public string Discriminator { get; set; }
        public string country { get; set; }
        public int postcode { get; set; }
        public string street { get; set; }
        public string city { get; set; }
        public string state { get; set; }
        public System.DateTime dob { get; set; }
        public Nullable<int> gender { get; set; }
        public bool willingToShowPhoneNum { get; set; }
        public bool willingToShowDOB { get; set; }
        public bool willingToShowAddress { get; set; }
        public bool willingToshowEmail { get; set; }
        public bool wantsToReceiveTexts { get; set; }
        public int status { get; set; }
    
        public virtual ICollection<APIKEY> APIKEYs { get; set; }
        public virtual ICollection<AspNetUserClaim> AspNetUserClaims { get; set; }
        public virtual ICollection<AspNetUserLogin> AspNetUserLogins { get; set; }
        public virtual ICollection<Event> Events { get; set; }
        public virtual ICollection<INFRACTION> INFRACTIONS { get; set; }
        public virtual ICollection<PLAYER> PLAYERs { get; set; }
        public virtual ICollection<REFEREE> REFEREEs { get; set; }
        public virtual ICollection<TEAM> TEAMs { get; set; }
        public virtual ICollection<TOURNAMENT> TOURNAMENTs { get; set; }
        public virtual ICollection<AspNetRole> AspNetRoles { get; set; }
        public virtual ICollection<TOURNAMENT> TOURNAMENTs1 { get; set; }


        public void GetObjectData(SerializationInfo info, StreamingContext ctxt)
        {
            info.AddValue("firstName", firstName);
            info.AddValue("UserName", UserName);
            if (ffaNum != null)
            {
                info.AddValue("ffaNum", ffaNum);
            }

            info.AddValue("lastName", lastName);
            if (phoneNum != null)
            {
                info.AddValue("phoneNum", phoneNum);
            }


            info.AddValue("email", email);

            info.AddValue("country", country);
            info.AddValue("postcode", postcode);
            info.AddValue("street", street);
            info.AddValue("city", city);
            info.AddValue("state", state);
            info.AddValue("dob", dob);
            info.AddValue("willingToShowPhoneNum", willingToShowPhoneNum);
            info.AddValue("willingToShowDOB", willingToShowDOB);
            info.AddValue("willingToShowAddress", willingToShowAddress);
            info.AddValue("willingToshowEmail", willingToshowEmail);
            info.AddValue("wantsToReceiveTexts", wantsToReceiveTexts);
            info.AddValue("photoDir", photoDir);
          }

    }
}
