
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace userprofile.Models
{

using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    
public partial class AspNetUserClaim
{

    public int Id { get; set; }
    [DisplayName("Claim Type")]
    public string ClaimType { get; set; }
    [DisplayName("Claim Valuee")]
    public string ClaimValue { get; set; }
     [DisplayName("User Id")]
    public string User_Id { get; set; }



    public virtual AspNetUser AspNetUser { get; set; }

}

}
