//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace userprofile.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class INFRACTION
    {
        public int infractionId { get; set; }
        public string type { get; set; }
        public int status { get; set; }
        public int matchID { get; set; }
        public int player { get; set; }
        public System.DateTime expiryDate { get; set; }
        public int active { get; set; }
    
        public virtual MATCH MATCH { get; set; }
    }
}
