//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace userprofile.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LOCATION
    {
        public LOCATION()
        {
            this.MATCHes = new HashSet<MATCH>();
            this.REFEREEs = new HashSet<REFEREE>();
        }
    
        public int locationId { get; set; }
        public string name { get; set; }
        public Nullable<double> price { get; set; }
        public string street { get; set; }
        public string city { get; set; }
        public int postcode { get; set; }
        public int phoneNum { get; set; }
        public string country { get; set; }
        public string state { get; set; }
        public int active { get; set; }
    
        public virtual ICollection<MATCH> MATCHes { get; set; }
        public virtual ICollection<REFEREE> REFEREEs { get; set; }
    }
}
