//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace userprofile.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class MATCH
    {
        public MATCH()
        {
            this.INFRACTIONS = new HashSet<INFRACTION>();
            this.OFFERs = new HashSet<OFFER>();
        }

        [Display(Name = "Match Id")]
        public int matchId { get; set; }
        [Display(Name = "Match Date")]
        [Required(ErrorMessage = "Match Date required")]
        public System.DateTime matchDate { get; set; }
        [Display(Name = "Location Id")]
        [Required(ErrorMessage = "Location is required")]
        public Nullable<int> locationId { get; set; }
        [Display(Name = "Home Team")]
        [Required(ErrorMessage = "Home Team Name is required")]
        public int teamAId { get; set; }
        [Display(Name = "Away Team")]
        [Required(ErrorMessage = "Away Team Name is required")]
        public int teamBId { get; set; }
        [Display(Name = "Home Team Score")]
        public Nullable<int> teamAScore { get; set; }
        [Display(Name = "Away Team Score")]
        public Nullable<int> teamBScore { get; set; }
        [Display(Name = "Status")]
        public Nullable<int> status { get; set; }
        [Display(Name = "Tournament Id")]
        public int tournamentId { get; set; }
        [Display(Name = "Match Duration")]
        [Required(ErrorMessage = "Match Duration is required")]
        public int matchLength { get; set; }
        [Display(Name = "Half Time Duration")]
        [Required(ErrorMessage = "Half Time Duration is required")]
        public int halfTimeDuration { get; set; }
        [Display(Name = "Match counts towards point system")]
        public bool countsToDraw { get; set; }
    
        public virtual ICollection<INFRACTION> INFRACTIONS { get; set; }
        public virtual LOCATION LOCATION { get; set; }
        public virtual TEAM TEAM { get; set; }
        public virtual TEAM TEAM1 { get; set; }
        public virtual TOURNAMENT TOURNAMENT { get; set; }
        public virtual ICollection<OFFER> OFFERs { get; set; }
    }
}
