//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace userprofile.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OFFER
    {
        public OFFER()
        {
            this.OFFERQUALs = new HashSet<OFFERQUAL>();
            this.REFEREEs = new HashSet<REFEREE>();
        }
    
        public int offerId { get; set; }
        public int matchId { get; set; }
        public Nullable<int> refId { get; set; }
        public int status { get; set; }
        public System.DateTime dateOfOffer { get; set; }
        public string declinedReason { get; set; }
        public int priority { get; set; }
        public string typeOfOffer { get; set; }
    
        public virtual MATCH MATCH { get; set; }
        public virtual ICollection<OFFERQUAL> OFFERQUALs { get; set; }
        public virtual REFEREE REFEREE { get; set; }
        public virtual TYPE TYPE { get; set; }
        public virtual ICollection<REFEREE> REFEREEs { get; set; }
    }
}
