
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace userprofile.Models
{

using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    
public partial class PLAYER
{

    public int team { get; set; }
    [DisplayName("ID")]
    public string ID { get; set; }
    [DisplayName("Position")]
    public string position { get; set; }

    public Nullable<int> shirtNum { get; set; }



    public virtual AspNetUser AspNetUser { get; set; }

    public virtual TEAM TEAM1 { get; set; }

}

}
