
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace userprofile.Models
{

using System;
    using System.Collections.Generic;
    
public partial class QUALIFICATION
{

    public QUALIFICATION()
    {

        this.REFEREEs1 = new HashSet<REFEREE>();

        this.OFFERs = new HashSet<OFFER>();

    }


    public int qID { get; set; }

    public string name { get; set; }

    public string sport { get; set; }

    public string supDesc { get; set; }



    public virtual SPORT SPORT1 { get; set; }

    public virtual ICollection<REFEREE> REFEREEs1 { get; set; }

    public virtual ICollection<OFFER> OFFERs { get; set; }

}

}
