//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace userprofile.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class REFEREE
    {
        public REFEREE()
        {
            this.OFFERs = new HashSet<OFFER>();
            this.USERQUALs = new HashSet<USERQUAL>();
        }
    
        public int refID { get; set; }
        public Nullable<int> distTravel { get; set; }
        public string sport { get; set; }
        public Nullable<int> prefAge { get; set; }
        public Nullable<int> prefGrade { get; set; }
        public string ID { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual ICollection<OFFER> OFFERs { get; set; }
        public virtual SPORT SPORT1 { get; set; }
        public virtual TIMEOFF TIMEOFF { get; set; }
        public virtual ICollection<USERQUAL> USERQUALs { get; set; }
        public virtual WEEKLYAVAILABILITY WEEKLYAVAILABILITY { get; set; }
    }
}
