//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace userprofile.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SCORE
    {
        public int score1 { get; set; }
        public string player { get; set; }
        public int matchID { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual MATCH MATCH { get; set; }
    }
}
