//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace userprofile.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class TEAM
    {
        public TEAM()
        {
            this.MATCHes = new HashSet<MATCH>();
            this.MATCHes1 = new HashSet<MATCH>();
            this.PLAYERs = new HashSet<PLAYER>();
            this.TOURNAMENTs = new HashSet<TOURNAMENT>();
        }

        [Display(Name = "Team Id")]
        public int teamId { get; set; }
         [Display(Name = "Team Name")]
        public string name { get; set; }
         [Display(Name = "Age Group")]
        public Nullable<int> ageBracket { get; set; }
         [Display(Name = "Grade")]
        public string grade { get; set; }
         [Display(Name = "Sport")]
        public string sport { get; set; }
         [Display(Name = "Manager Id")]
        public string managerId { get; set; }
         [Display(Name = "Short Name")]
        public string shortName { get; set; }
         [Display(Name = "Status")]
        public int status { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual ICollection<MATCH> MATCHes { get; set; }
        public virtual ICollection<MATCH> MATCHes1 { get; set; }
        public virtual ICollection<PLAYER> PLAYERs { get; set; }
        public virtual SPORT SPORT1 { get; set; }
        public virtual ICollection<TOURNAMENT> TOURNAMENTs { get; set; }
    }
}
