//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace userprofile.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TEAMIN
    {
        public int teamID { get; set; }
        public int tournament { get; set; }
        public int currentPosition { get; set; }
        public int points { get; set; }
        public int wins { get; set; }
        public int draws { get; set; }
        public int losses { get; set; }
        public int goalsFor { get; set; }
        public int goalsAgainst { get; set; }
        public int goalDraw { get; set; }
        public int status { get; set; }
    
        public virtual TEAM TEAM { get; set; }
        public virtual TOURNAMENT TOURNAMENT1 { get; set; }
    }
}
